[versions]
assertJ = "3.27.7"
buildTimeTracker = "5.0.1"
detekt = "2.0.0-alpha.2"
grgit = "5.3.3"
junit = "6.0.3"
kotlin = "2.3.10"
kover = "0.9.1"
release = "3.1.0"
versionCatalogUpdate = "1.1.0"

[libraries]
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
grgit = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
buildTimeTracker = { id = "com.asarkar.gradle.build-time-tracker", version.ref = "buildTimeTracker" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
release = { id = "net.researchgate.release", version.ref = "release" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
